#!/bin/sh -e

echo "Starting Bash Script"

#checking for existing git repos
export variable=`pwd`

echo "Checking For Existing Git Repository"

if [ -d "$variable"/.git ]; then
    
    echo "Clearing Existing Git Repository"
    
    rm -rf .git
    
    echo "Git Repository Cleared"

else
	echo "No Git Repository Found"

fi

if [ -d "$variable"/logs ]; then

	echo "Logs Repository Found"

else    
	echo "Creating Logs Directory"

	mkdir logs

	echo "Logs Directory Creation Complete"

fi

# Initization of Git Repository
echo "Initializing Fresh Git Repository"

git init

echo "Repository Initialization Successful"

#installing NPM Modules
echo "Installing NPM Modules"

npm install 

echo "NPM Install Complete"

echo "Removing Git Ignore"

rm -rf .gitignore

echo "Creating Git Ignore"

touch .gitignore

echo "# Logs" >> .gitignore
echo "logs" >> .gitignore
echo "*.log" >> .gitignore
echo "npm-debug.log*" >> .gitignoreecho "" >> .gitignore

echo "" >> .gitignore

echo "# Runtime data" >> .gitignore
echo "pids" >> .gitignore
echo "*.pid" >> .gitignore
echo "*.seed" >> .gitignore
echo "" >> .gitignore

echo "# Directory for instrumented libs generated by jscoverage/JSCover" >> .gitignore
echo "lib-cov" >> .gitignore
echo "" >> .gitignore

echo "# Coverage directory used by tools like istanbul" >> .gitignore
echo "coverage" >> .gitignore
echo "" >> .gitignore

echo "# nyc test coverage" >> .gitignore
echo ".nyc_output" >> .gitignore
echo "" >> .gitignore

echo "# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)" >> .gitignore
echo ".grunt" >> .gitignore
echo "" >> .gitignore

echo "# node-waf configuration" >> .gitignore
echo ".lock-wscript" >> .gitignore
echo "" >> .gitignore

echo "# Compiled binary addons (http://nodejs.org/api/addons.html)" >> .gitignore
echo "build/Release" >> .gitignore
echo "" >> .gitignore

echo "# Dependency directories" >> .gitignore
echo "node_modules" >> .gitignore
echo "jspm_packages" >> .gitignore
echo "bower_components" >> .gitignore
echo "" >> .gitignore

echo "# Optional npm cache directory" >> .gitignore
echo ".npm" >> .gitignore
echo "" >> .gitignore

echo "# Optional REPL history" >> .gitignore
echo ".node_repl_history" >> .gitignore
echo "" >> .gitignore

echo "#Removing Uploads" >> .gitignore
echo "uploads" >> .gitignore
echo "auth_config" >> .gitignore
echo "ssl" >> .gitignore
echo "" >> .gitignore

echo ".gitignore Created"


echo "Removing the Shell Script"

rm -rf 'initScript.sh'

echo "Init ShellScript Deleted."


